name: TF Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: TF Plan
    runs-on: ubuntu-latest
    outputs:
      plan-file: ${{ steps.publish.outputs.plan-file }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.3"

      - name: Config aws OIDC
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-region: ap-south-2
          role-to-assume: ${{ vars.AWS_ROLE }}

      - name: Configure Terraform plugin cache
        run: |
          echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
          mkdir --parents "$HOME/.terraform.d/plugin-cache"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: tf-dep-provider-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: TF INIT
        run: terraform init -input=false

      - name: TF Plan
        run: terraform plan -no-color -input=false -out tfplan.tfplan

      - name: Publish plan filename
        id: publish
        run: find ./*.tfplan -type f -execdir echo 'plan-file={}' >> $GITHUB_OUTPUT ';'

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: tf-plan
          path: tfplan.tfplan

  apply:
    name: TF Apply
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.3"

      - name: Configure aws OIDC
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-region: ap-south-2
          role-to-assume: ${{ vars.AWS_ROLE }}

      - name: Output file name
        run: echo "${{ needs.plan.outputs.plan-file }}"

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: tf-plan

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: tf-dep-provider-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Terraform INIT
        run: terraform init -input=false

      - name: Terraform apply
        run: terraform apply -auto-approve ${{ needs.plan.outputs.plan-file }}
